Adds more functionality to reindexing tasks
pulibrary/pomegranate pull request #831
Opened 2020-09-14 20:38 UTC by hackmastera

closes #533

2020-09-14 20:56 UTC, eliotjordan requested changes

2020-09-14 20:56 UTC, eliotjordan commented on lib/tasks/index.rake
> +    noid = args[:noi]
Should be `args[:noid]`.

2020-09-15 12:31 UTC, hackmastera commented on lib/tasks/index.rake
> +    noid = args[:noi]
Thanks @eliotjordan! this is fixed.

2020-09-15 16:25 UTC, eliotjordan approved these changes

2020-09-15 16:25 UTC, merged